spring:
  application:
    name: TramTruyenAPI

  # C?u h�nh k?t n?i PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/tramtruyen_db
    username: dev_user
    password: dev_password123
    driver-class-name: org.postgresql.Driver

  # C?u h�nh Hibernate (T? ??ng sinh b?ng - ch? d�ng cho Dev)
  jpa:
    hibernate:
      ddl-auto: update # T? ??ng t?o/c?p nh?t c?t trong DB d?a tr�n Entity Java
    show-sql: true     # In c�u l?nh SQL ra console ?? d? debug
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000